#!/usr/bin/env python3
# This file is placed in the Public Domain.


import doctest
import inspect
import os
import shutil
import sys
import time
import unittest


sys.path.insert(0, os.getcwd())


from gcid.obj import Config, format
from gcid.cbs import Callbacks
from gcid.cmd import dispatch
from gcid.scn import scan
from gcid.shl import CLI


import gcid.cmds


flags = doctest.REPORT_NDIFF | doctest.FAIL_FAST | doctest.ELLIPSIS
results = []


Config.debug = True
Config.workdir = ".test"


class CLI(CLI):

    def raw(self, txt):
        if Config.verbose:
            print(txt)


c = CLI()


def main():
    Callbacks.add("command", dispatch)
    if os.path.exists(".test"):
        shutil.rmtree(".test")
    print("GCIDE tests started at %s" % time.ctime(time.time()).replace("  ", " "))
    if "-v" in sys.argv:
        Config.verbose = True
    print(format(Config))
    scan("gcid")
    pat = "test_%s*" % "*"
    suite = unittest.loader.TestLoader().discover("test", pattern=pat)
    unittest.TextTestRunner(verbosity=3).run(suite)


main()
